# -*- coding: utf-8 -*-
"""Uzman değerlendirme formunun madde listesi + form üreteci."""

# (id, bölüm, çapa=metinde geçen benzersiz dizge, işaret=koyu-italik yapılacak dizge, soru)
MADDELER = [
# ---------------- A: test ve doku seçimi ----------------
("A1", "03", "Nokta LoF varyantları için **dizileme (WES/WGS)**",
 "ikisi **birlikte** istenmelidir",
 "Haploinsufficiency geninde dizileme ve doz analizinin *birlikte* istenmesi kuralı — pratikte her zaman geçerli mi, yoksa gen/test menüsüne göre kademelendirilmeli mi?"),
("A2", "08", "Bu nedenle CMA **birinci-basamak sitogenetik test**",
 "karyotip ise belirgin kromozomal sendrom düşünülen olgular, ailede dengeli yeniden düzenlenme öyküsü veya tekrarlayan düşük öyküsü için saklanır",
 "Karyotipin hangi durumlar için saklanacağı listesi eksiksiz mi? Türkiye pratiğinde bu öneri uygulanabilir mi?"),
("A3", "08", "**CMA negatif diye dengeli/mozaik varyantı dışlamak.**",
 "bu iki durum bu hasta grubunda anormal fenotipin **<%1**'ini açıklar — CMA'yı birinci basamaktan indirmenin gerekçesi değildir",
 "\"<%1\" oranı ve buradan çıkarılan pratik sonuç doğru mu?"),
("A4", "09", "WES negatifliği tekrar hastalığını ekarte etmez",
 "hedefli PCR veya long-read WGS yapılmalıdır",
 "Hedefli PCR mı, long-read WGS mi önce gelmeli? Listelenen klinik tablolar (ataksi, miyotoni, EY, nörodejenerasyon) yeterli mi?"),
("A5", "09", "Çocuklara rutin presemptomatik HD testi yapılması önerilmez",
 "Çocuklara rutin presemptomatik HD testi yapılması önerilmez",
 "Bu normatif ifade, ulusal/uluslararası kılavuzlarla uyumlu mu? İstisnaları (semptomatik çocuk, juvenil HD şüphesi) belirtilmeli mi?"),
("A6", "10", "İlk basamak daima **metilasyon-duyarlı bir test**",
 "İlk basamak daima **metilasyon-duyarlı bir test**tir",
 "\"Daima\" ifadesi doğru mu? Klinik tablo çok tipikse doğrudan alt-tip testine gidilebilir mi?"),
("A7", "10", "**Metilasyon anormalliğini alt-tiple karıştırmak.**",
 "tekrarlanma riski için alt-tip şarttır",
 "Alt-tip belirlemenin danışma için şart olduğu ifadesi ve önerilen sıralama doğru mu?"),
("A8", "10", "ICR mikrodelesyonu açısından incelenmelidir",
 "\"epigenetik = sporadik\" varsayımı tehlikelidir",
 "\"Mutlaka incelenmelidir\" ifadesi pratikte uygulanabilir mi (test erişimi)? Hangi lokuslarda öncelikli?"),
("A9", "10", "gen skoruna değil bölge kaydına ve metilasyon paternine",
 "İmprintli bir lokusta refleks, **gen skoruna değil bölge kaydına ve metilasyon paternine** bakmaktır",
 "Bu refleks doğru formüle edilmiş mi?"),
("A10", "11", "çocukta kan sıklıkla yeterlidir; erişkinde ve şüphe sürüyorsa idrar epiteli veya kas",
 "çocukta kan sıklıkla yeterlidir; erişkinde ve şüphe sürüyorsa idrar epiteli veya kas",
 "Doku sıralaması ve yaş ayrımı doğru mu? Kas biyopsisinin yeri günümüzde nerede?"),
("A11", "11", "\"WES yaptık, mtDNA da bakılmış olur.\"",
 "mtDNA hedefli analiz veya WGS gerekir",
 "Modern WES protokollerinde mtDNA kapsaması arttı mı? Bu uyarı hâlâ geçerli mi?"),
("A12", "11", "\"Kanda mtDNA analizi negatif geldi, mitokondriyal hastalık dışlandı.\"",
 "Şüphe sürüyorsa idrar epiteli veya kas örneklenmelidir",
 "m.3243A>G özelinde verilen bu uyarı diğer varyantlara genellenebilir mi?"),
("A13", "11", "düzenli EKG izlemi zorunludur",
 "kardiyak ileti bozukluğu ani ölüm riski taşıdığı için düzenli EKG izlemi zorunludur",
 "İzlem sıklığı belirtilmeli mi? Holter/pacemaker eşiği eklenmeli mi?"),
("A14", "11", "MITOMAP ve HelixMTdb",
 "genel nükleer frekans eşikleri doğrudan aktarılamaz",
 "Veri tabanı seçimi ve haplogrup uyarısı yeterli mi?"),
("A15", "12", "bir deri lezyonu bu çizgileri izliyorsa",
 "test için kan değil, **lezyonlu deri** istenmelidir",
 "\"Neredeyse kesinlikle mozaik varyant vardır\" ifadesinin kesinlik derecesi uygun mu?"),
("A16", "12", "kan **kesinlikle** yanlış dokudur",
 "tek bir deri lezyonuyla sınırlı bir tabloda kan **kesinlikle** yanlış dokudur",
 "\"Kesinlikle\" sözcüğü burada gerekli mi, yoksa yumuşatılmalı mı?"),
("A17", "12", "Mozaiklik şüphesinde derin hedefli panel veya ddPCR gerekir",
 "Mozaiklik şüphesinde derin hedefli panel veya ddPCR gerekir",
 "Hedef derinlik değeri verilmeli mi (ör. ≥1000×)? ddPCR yerine amplikon NGS önerilmeli mi?"),
("A18", "12", "klonal hematopoez",
 "**ikinci bir dokuyla** doğrulanmadan kurulmamalıdır",
 "Klonal hematopoez ayrımı için yaş eşiği/VAF eşiği verilmeli mi?"),
("A19", "12", "yeterli sayıda hücre sayılmış olması",
 "klasik karyotipte mozaikliği dışlamak için **yeterli sayıda hücre sayılmış olması** gerekir",
 "Sayı verilmeli mi (ör. 30–50 metafaz, düşük mozaiklikte daha fazla)?"),
("A20", "13", "**ekzom yetmez, WGS gerekir**",
 "bu varyantları görmek için **ekzom yetmez, WGS gerekir**",
 "Üç klinik sonucun tamamı doğru mu? \"Dar ve tek organa sınırlı fenotip\" genellemesi tutar mı?"),
("A21", "07", "Etkinin *kanıtı* için ise RNA-seq",
 "Etkinin *kanıtı* için ise RNA-seq veya hedefe yönelik cDNA/RT-PCR gerekir",
 "Doğru doku şartı ve minigen assay'in yeri yeterince vurgulanmış mı?"),
("A22", "15", "Allelik serilerde test seçiminin belirleyicisi cihaz değil",
 "Allelik serilerde test seçiminin belirleyicisi cihaz değil, **hangi hastalığın arandığı varsayımıdır.**",
 "Bu ilke pratikte uygulanabilir mi, yoksa gen tamamının bakılması artık varsayılan mı?"),
("A23", "17", "kas dokusundan RNA dizileme",
 "**kas dokusundan RNA dizileme**",
 "Bu senaryoda kas biyopsisi önerisi Türkiye koşullarında gerçekçi mi? Fibroblast alternatif olabilir mi?"),
("A24", "11", "Nükleer mitokondriyal genleri (~1500) iyi kapsar",
 "mtDNA kapsaması standart değildir; heteroplazmi ölçümü güvenilir değildir",
 "Bu, her bölümde tekrarlanan **standart test tablosunun** bir örneğidir. Sekiz satırın (WES · short-read WGS · long-read WGS · array · MLPA · RNA-seq · metilasyon array · karyotip) \"yakalar mı / sınırlılığı\" değerlendirmeleri toptan doğru mu? Düzeltilmesi gereken hücre var mı?"),

# ---------------- B: sayısal eşikler ve basitleştirmeler ----------------
("B1", "01", "\"polimorfizm\" ise popülasyonda yaygın",
 "genellikle %1'den sık",
 "%1 eşiği hâlâ öğretilmeli mi, yoksa terk edilmiş bir tanım olarak mı sunulmalı?"),
("B2", "01", "risk asla tam olarak sıfır değildir",
 "risk asla tam olarak sıfır değildir",
 "Gonadal mozaiklik nedeniyle verilen bu ifade doğru mu? Sayısal bir tekrarlanma riski (%1–2 gibi) verilmeli mi?"),
("B3", "01", "Sayısal örnekler (penetrans için 6/8 gibi)",
 "belirli bir çalışmadan değil, kavramı göstermek için temsilî olarak verilmiştir",
 "Temsilî sayı kullanımı öğretici mi, yoksa gerçek bir gen üzerinden gerçek penetrans verisi mi kullanılmalı?"),
("B4", "02", "NMD eşik kuralı (son ekzon-ekzon bağlantısı ~50 nt)",
 "öğretici basitleştirmedir; gen/transkripte göre istisnalar olabilir",
 "50 nt kuralının bu şekilde sunulması yeterli mi? İstisnalar (son ekzon, ilk 150 nt, uzun 3'UTR) örneklenmeli mi?"),
("B5", "02", "\"Son ekzon = her zaman hafif/benign\" varsayımı",
 "bu nedenle **yanlıştır**",
 "Bu uyarı doğru mu? Son ekzon varyantlarının ne zaman ağır olduğu yeterince açıklanmış mı?"),
("B6", "03", "aynı %50 fiziksel kayıp, eğrinin dikliğine",
 "\"varyant %50 kayıp yapıyor\" bilgisi tek başına fenotip hakkında hiçbir şey söylemez",
 "Doz–yanıt eğrisi çerçevesi öğretici olarak doğru mu? Aşırı basitleştirme riski var mı?"),
("B7", "03", "metabolik kontrol analizinde verilmiştir",
 "resesifliğin yaygınlığı, seçilimle kazanılmış bir \"güvenlik payı\" değil, enzim ağının kinetik yapısının doğrudan sonucudur",
 "Kacser & Burns (1981) çerçevesinin bu kadar kesin sunulması doğru mu? Bu tez literatürde tartışmalı mı?"),
("B8", "04", "nonsense/frameshift ise GoF için tipik olarak *beklenmez*",
 "nonsense/frameshift ise GoF için tipik olarak *beklenmez*",
 "Bu genelleme doğru mu? İstisnalar (ör. son ekzon kesilmesiyle otoinhibisyon kaybı) belirtilmeli mi?"),
("B9", "04", "\"fazla sinyal\" her zaman \"fazla büyüme\" demek değildir",
 "**hangi yolakta** fazlalık olduğu belirleyicidir",
 "FGFR3 üzerinden kurulan bu ders doğru mu?"),
("B10", "05", "**DN trimerde** (n=3",
 "**DN trimerde** (n=3, örneğin kollajen) oran (½)³ = **⅛ (~%12)**",
 "Bu multimer matematiği \"rastgele birleşme + ½ varyant alt birim\" varsayımıyla temsilî veriliyor. Öğretici mi, yanıltıcı mı? Kollajen için gerçek oran farklı mı?"),
("B11", "05", "Haploinsufficiency işlevi ~%50'ye indirirken",
 "DN onu kompleks büyüklüğüne göre %25'e, %12'ye veya daha aşağıya çeker",
 "\"DN her zaman HI'dan ağırdır\" genellemesi doğru mu?"),
("B12", "05", "glisin, sarmalın iç eksenine sığabilen tek küçük amino asittir",
 "özellikle sarmal boyunca her üçüncü konumdaki **glisinlerin** korunması gerekir",
 "Kollajen glisin kuralının bu biçimde anlatımı doğru mu?"),
("B13", "05", "\"Kısaltıcı varyant her zaman en kötü\" değildir",
 "Sezgi, protein üretimini erken durduran (nonsense/frameshift) varyantların missense'ten daha ağır olacağını söyler",
 "OI üzerinden kurulan bu ters-sezgi dersi doğru mu?"),
("B14", "06", "IDH1'de neredeyse daima Arg132",
 "IDH1'de neredeyse daima Arg132, IDH2'de Arg172/Arg140; histon H3'te Lys27",
 "Hotspot listesi doğru ve güncel mi? H3K27M için gen adı (H3-3A/H3C2) belirtilmeli mi?"),
("B15", "09", "Tüm tekrar eşiği sayısal değerleri",
 "\"temsilî\" olarak verilmiştir; klinik kullanımda güncel gen-spesifik lab kılavuzları tercih edilmelidir",
 "Eşikleri temsilî bırakıp kılavuza yönlendirmek doğru bir tercih mi, yoksa net bir tablo mu verilmeli?"),
("B16", "09", "neredeyse her zaman etkilenmiş anneden",
 "genellikle >1000",
 "CDM1 için verilen \"neredeyse her zaman anneden\" ve \">1000 CTG\" ifadeleri doğru mu?"),
("B17", "11", "izole Kompleks II eksikliği hiçbir zaman maternal kalıtılmaz",
 "Kompleks II tümüyle nükleer kodludur; dolayısıyla izole Kompleks II eksikliği hiçbir zaman maternal kalıtılmaz",
 "Kompleks II ve Kompleks I alt birim sayıları (45 alt birimin 7'si mtDNA) doğru mu?"),
("B19", "11", "neredeyse her zaman **çok sistemli**",
 "neredeyse her zaman **çok sistemli** ama **nörolojik ve kardiyak ağırlıklı**",
 "Bu genelleme doğru mu? İzole organ tutulumlu tablolar (LHON, izole miyopati) bu ifadeyi zayıflatıyor mu?"),
("B20", "11", "istisnasız görünen bir kural gibi davrandığını",
 "maternal kalıtımın neden istisnasız görünen bir kural gibi davrandığını açıklar",
 "Paternal mtDNA geçişi bildirimleri karşısında bu ifade nasıl konumlandırılmalı?"),
("B21", "12", "yalnızca %30'unu oluşturuyorsa",
 "ölçülen VAF gerçek klonal yükü olduğundan çok daha düşük gösterir",
 "Örnek saflığı anlatımı doğru mu? Düzeltme yapılabileceği (lezyon oranına bölme) belirtilmeli mi?"),
("B22", "14", "Digenik iddiayı kurmak için en az şu üçü gerekir",
 "**(1)** iki ürün arasında gösterilebilir **biyolojik bağ**",
 "Üç koşul yeterli mi? Fonksiyonel model (hücre/hayvan) dördüncü koşul olarak eklenmeli mi?"),
("B23", "14", "Trialelik kalıtımın BBS'deki kapsamı",
 "bu modelin her ailede geçerli olduğu varsayılmamalı",
 "Trialelik kalıtım uyarısı yeterince güçlü mü? Model bugün büyük ölçüde terk edildi mi?"),
("B24", "16", "En güçlü kriter olan PVS1 bile tek başına",
 "yanına en az bir destekleyici kanıt gerekir",
 "Bu ifade nokta puanlama sisteminde doğru mu?"),
("B25", "16", "destekleyici** güce indirilmiş biçimde",
 "orta güçte değil, günümüzde çoğu uzman grubunda **destekleyici** güce indirilmiş biçimde",
 "PM2'nin destekleyiciye indirilmesi genel geçer mi, yoksa VCEP'e göre değişiyor mu diye sunulmalı mı?"),
("B26", "16", "Toplam +11 → **patojenik**",
 "Toplam +11 → **patojenik**",
 "Bu çözümlü örneğin puanlaması doğru mu? PS3'ün tam güçte (+4) kullanılması bu veriyle savunulabilir mi?"),
("B27", "17", "tüm genom dizilemenin tanısal getirisini 0,41",
 "tüm genom dizilemenin tanısal getirisini 0,41, tüm ekzom dizilemeninkini 0,36 ve kromozomal mikroarray'inkini 0,10",
 "Bu meta-analiz sayıları Türkiye pratiğine beklenti olarak aktarılabilir mi? Daha güncel getiri verisi kullanılmalı mı?"),

# ---------------- C: kaynaksız mekanizma / ders bilgisi ----------------
("C1", "01", "akraba evliliği riski belirgin biçimde artırır",
 "akraba evliliği riski belirgin biçimde artırır",
 "Kalıtım kalıplarının özet tanımları doğru ve eksiksiz mi? Akraba evliliği ifadesi Türkiye bağlamında genişletilmeli mi?"),
("C2", "01", "referans dizi her zaman \"sağlıklı\" anlamına gelmez",
 "**referans dizi her zaman \"sağlıklı\" anlamına gelmez**; referansta da patojen aleller bulunabilir",
 "Bu uyarı doğru mu? Örnek verilmeli mi?"),
("C3", "01", "bu metrikler **gen düzeyinde** önceliklendirme araçlarıdır",
 "resesif hastalık yapan LoF genleri (hastalık için iki kopyanın da kaybı gerektiğinden) popülasyonda \"tolerant\" görünebilir",
 "Constraint metriklerinin sınırları doğru anlatılmış mı?"),
("C4", "02", "| **Hipomorfik allel** |",
 "Azalmış ama sıfır olmayan işlev",
 "Kavram tablosundaki tanımlar (null/amorf, hipomorfik, LoF) doğru ve Türkçe karşılıkları uygun mu?"),
("C5", "03", "balance hypothesis",
 "balance hypothesis",
 "\"Dengeli ifade hipotezi\" bu adla anılıyor mu ve burada doğru kullanılmış mı? (Kitapta kaynaksız.)"),
("C6", "03", "morfojen",
 "morfojen",
 "Morfojen gradyanı ve eşik-bağımlı hücre kaderi anlatımı doğru mu? (Kitapta kaynaksız, \"yerleşik ders bilgisi\" olarak etiketli.)"),
("C7", "03", "Eşikten uzak (çok düşük doz) varyantlarda",
 "eşiğe yakın doz bırakanlarda penetrans eksik, ekspresivite değişken olur",
 "HI'da değişken penetransın eşik-yakınlığıyla açıklanması doğru mu?"),
("C8", "05", "DN'in iki ön koşulu",
 "Bir varyantın DN etki yapabilmesi için iki şart gerekir",
 "İki ön koşul doğru ve yeterli mi?"),
("C9", "05", "missense-ağırlıklı** ve **multimerik",
 "Dominant, ağır, **missense-ağırlıklı** ve **multimerik/kompleks** bir protein → dominant-negatifi erken düşün",
 "Bu klinik pusula güvenilir mi, yoksa fazla kestirme mi?"),
("C10", "06", "toksik kazanım da neomorfik gibi",
 "toksik kazanım da neomorfik gibi \"varyant ürünün zararlı varlığından\" doğar, dolayısıyla dominanttır",
 "Toksik kazanımın neomorfikle bu şekilde yan yana konması kavramsal olarak doğru mu?"),
("C11", "07", "| Varyant tipi (yer) | Tipik splicing sonucu |",
 "| Varyant tipi (yer) | Tipik splicing sonucu |",
 "Varyant tipi → tipik splicing sonucu tablosunun tüm satırları doğru mu?"),
("C12", "10", "izolatör (insulator)",
 "Metilasyonun aleli her zaman doğrudan susturmadığını vurgulamak gerekir; kimi ICR'ler bir **izolatör (insulator)** üzerinden çalışır",
 "İzolatör mekanizması (H19/IGF2, CTCF) doğru anlatılmış mı?"),
("C13", "10", "İzodizomi neden iki ayrı yolla hastalık yapar",
 "UPD'nin iki ayrı patojenik yüzü vardır",
 "İzodizominin iki mekanizması (imprint dengesizliği + resesif varyantın homozigotlaşması) doğru ayrılmış mı?"),
("C14", "10", "UPD'yi klinik olarak anlamak için oluşum mekanizmasını bilmek şarttır",
 "mekanizma hem **hangi lokusların homozigot olduğunu** hem de **tekrarlanma riskini** belirler",
 "UPD oluşum mekanizmalarının (trizomi kurtarma, monozomi kurtarma, gamet tamamlama) klinik sonuçlara bağlanması doğru mu?"),
("C15", "12", "**Letal-mozaik hipotezi**, bazı varyantların",
 "bu hipotez, bir grup sendromun neden istisnasız sporadik olduğunu açıklar",
 "Happle'ın letal-mozaik hipotezi bugün hâlâ geçerli mi? \"Daima sporadik\" ifadesi tutuyor mu?"),
("C16", "12", "*\"Hastanın fenotipini ne açıklıyor?\"*",
 "*\"Kardeşinde tekrar eder mi?\"* sorusunun cevabı ise **germ hücresi bölmesindedir**",
 "İki sorunun bu şekilde ayrılması danışma pratiğinde doğru mu?"),
("C17", "12", "**Revertant mozaiklik** ise ters yöndeki olaydır",
 "**Revertant mozaiklik** ise ters yöndeki olaydır",
 "Revertant mozaiklik anlatımı doğru mu? Bu konu bir textbook'ta bu ağırlıkta yer almalı mı?"),
("C18", "13", "dar ve tek organa sınırlıdır",
 "fenotip çoğu zaman şaşırtıcı biçimde **dar ve tek organa sınırlıdır**, çünkü etkilenen düzenleyici doku-özgüdür",
 "Bu genelleme doğru mu? PVS1'in uygulanamaması ve ağırlığın fonksiyonel deneye kayması ifadesi de değerlendirilsin."),
("C20", "15", "⚠️ Dolayısıyla domain–fenotip haritaları",
 "domain–fenotip haritaları güçlü **örüntüler** sunar, ancak birebir öngörü aracı olarak kullanılmamalıdır",
 "Domain–fenotip haritalarının sınırı doğru çizilmiş mi?"),
("C21", "15", "*COL4A3*/*COL4A4*",
 "**yerleşik ders bilgisi** düzeyinde verilmiştir; bu bölümde ayrıca PubMed doğrulaması yapılmamıştır",
 "COL4A3/COL4A4 ve RYR1 örneklerinin kaynaksız, ders bilgisi olarak verilmesi kabul edilebilir mi? İçerik doğru mu?"),
("C22", "15", "*FGFR3* varyant–fenotip eşleşmeleri",
 "yerleşik klinik genetik bilgisidir",
 "Listelenen FGFR3 varyant–fenotip eşleşmelerinin tamamı doğru mu?"),
("C23", "15", "Hotspot her zaman bir hastalığın hotspot'udur",
 "Hotspot her zaman bir hastalığın hotspot'udur",
 "PM1'in bu şekilde koşullanması doğru mu?"),
("C24", "17", "Mekanizma yönünü belirlemeden PS3 yorumlamak",
 "Mekanizma yönünü belirlemeden PS3 yorumlamak",
 "Hızlı-referans tablosundaki \"sık hata\" sütununun tüm satırları doğru mu?"),

# ---------------- D: özgün pedagojik çerçeveler (T5) ----------------
("D1", "01", "rezerv ve eşik",
 "bunları tek bir \"rezerv ve eşik\" başlığı altında toplamak kitabın pedagojik sentezidir",
 "Çerçeve pedagojik olarak sağlam mı? Etiket yeterince görünür mü? Kitapta kalsın mı?"),
("D2", "01", "**Penetrans** \"var mı?\" (Presence)",
 "🏷️ bu İngilizce baş harflere dayanan bellek desteği kitabın kendi anlatım aracıdır",
 "İngilizce baş harfe dayanan bir bellek desteği Türkçe bir kitapta işe yarar mı? Türkçe bir alternatif önerir misiniz?"),
("D3", "15", "altı eksenli çerçeve kitabın pedagojik sentezidir",
 "**\"allelik serinin altı ekseni\" literatürde bu adla yerleşik bir sınıflandırma değildir**",
 "Altı eksen doğru seçilmiş mi? Eksik/fazla eksen var mı? Çerçeve kitapta kalsın mı?"),
("D4", "17", "Şekil 17.3, bu bölümün ağırlık merkezidir",
 "kitabın on dört mekanizma bölümünün her birinin, sekiz kriter ailesiyle ilişkisini tek matriste özetler",
 "Matris pedagojik olarak sağlam mı? Normatif tabloyla karıştırılma riski yeterince önlenmiş mi?"),
("D5", "03", "Şekil 3.4 — Dozaj duyarlılığı spektrumu",
 "Dozaj duyarlılığı spektrumu ve onu ölçen metrikler",
 "Dozaj duyarlılığını bir spektrum olarak sunmak doğru mu? Metriklerin (pLI, LOEUF, pHaplo, pTriplo, HI-indeksi) tek eksene yerleştirilmesi yanıltıcı mı?"),
]
